#SingleInstance Force
#Persistent

#IfWinActive, ahk_exe cmd.exe
^v::SendInput, {Raw}%clipboard%
^x::WinClose, ahk_exe cmd.exe
::pf::%pf%
::pf64::%pf64%
::pf86::%pf86%
::pf32::%pf32%
::w::%w%
::sys32::%sys32%
::system32::%system32%
::u::%u%
::user::%user%
::dl::%dl%
::dls::%dls%
::downloads::%downloads%
::pics::%pics%
::pictures::%pictures%
::vids::%vids%
::videos::%videos%
::docs::%docs%
::documents::%documents%
::desktop::%desktop%
::dt::%dt%
::dropbox::%dropbox%
::db::%db%
::googledrive::%googledrive%
::gdrive::%gdrive%
::gd::%gd%
::pfdb::%pfdb%
::dbpf::%dbpf%
::dbsettings::%dbsettings%
::dbpfsettings::%dbpfsettings%
::pfdbsettings::%pfdbsettings%
::texts::%texts%
::books::%books%
::screenshots::%screenshots%
::school::%school%
::st::%st%
::st3::%st3%
::py2::%py2%
::py27::%py27%
::py::%py%
::py3::%py3%
::py34::%py34%
::cs113game::%cs113game%
::javac::%javac%
::allappdata::%allappdata%
::appdataall::%appdataall%
::roamingappdata::%roamingappdata%
::appdataroaming::%appdataroaming%
::rappdata::%rappdata%
::appdatar::%appdatar%
::localappdata::%localappdata%
::appdatalocal::%appdatalocal%
::lappdata::%lappdata%
::appdatal::%appdatal%
::gadgets::%gadgets%
::jetbrains::%jetbrains%
::startup::%startup%
::startup1::%startup1%
::startupall::%startupall%
::allstartup::%allstartup%
::startup2::%startup2%
::startupuser::%startupuser%
::userstartup::%userstartup%
#IfWinActive
