#SingleInstance Force
#Persistent

#IfWinActive, ahk_exe powershell.exe
^v::SendInput, {Raw}%clipboard%
^x::WinClose, ahk_exe powershell.exe
::pf::$env:pf
::pf64::$env:pf64
::pf86::$env:pf86
::pf32::$env:pf32
::w::$env:w
::sys32::$env:sys32
::system32::$env:system32
::u::$env:u
::user::$env:user
::dl::$env:dl
::dls::$env:dls
::downloads::$env:downloads
::pics::$env:pics
::pictures::$env:pictures
::vids::$env:vids
::videos::$env:videos
::docs::$env:docs
::documents::$env:documents
::desktop::$env:desktop
::dt::$env:dt
::dropbox::$env:dropbox
::db::$env:db
::googledrive::$env:googledrive
::gdrive::$env:gdrive
::gd::$env:gd
::pfdb::$env:pfdb
::dbpf::$env:dbpf
::dbsettings::$env:dbsettings
::dbpfsettings::$env:dbpfsettings
::pfdbsettings::$env:pfdbsettings
::texts::$env:texts
::books::$env:books
::screenshots::$env:screenshots
::school::$env:school
::st::$env:st
::st3::$env:st3
::py2::$env:py2
::py27::$env:py27
::py::$env:py
::py3::$env:py3
::py34::$env:py34
::cs113game::$env:cs113game
::javac::$env:javac
::allappdata::$env:allappdata
::appdataall::$env:appdataall
::roamingappdata::$env:roamingappdata
::appdataroaming::$env:appdataroaming
::rappdata::$env:rappdata
::appdatar::$env:appdatar
::localappdata::$env:localappdata
::appdatalocal::$env:appdatalocal
::lappdata::$env:lappdata
::appdatal::$env:appdatal
::gadgets::$env:gadgets
::jetbrains::$env:jetbrains
::startup::$env:startup
::startup1::$env:startup1
::startupall::$env:startupall
::allstartup::$env:allstartup
::startup2::$env:startup2
::startupuser::$env:startupuser
::userstartup::$env:userstartup
#IfWinActive
